{% set name = "fastapi" %}
{% set version = "0.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63c4592f5ef3edf30afa9a44fa7c6b7ccb20e0d3f68cd9eba07b44d552058dcb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
    - flit
  run:
    - python >=3.6
    - starlette-base =0.13.6
    - pydantic >=1.0.0,<2.0.0

test:
  imports:
    - fastapi
    - fastapi.dependencies
    - fastapi.middleware
    - fastapi.openapi
    - fastapi.security

about:
  home: https://github.com/tiangolo/fastapi
  license: MIT
  license_file: LICENSE
  license_url: https://github.com/tiangolo/fastapi/blob/master/LICENSE
  summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
  description: FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.7+ based on standard Python type hints.
  doc_url: https://github.com/tiangolo/fastapi
  doc_source_url: https://github.com/tiangolo/fastapi/tree/master/docs_src
  dev_url: https://github.com/tiangolo/fastapi

extra:
  skip-lints:
    - avoid_noarch
    - missing_pip_check
    - missing_license_family

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/26940
    reason: "needed for building vaex-server"
    recipe-maintainers:
      - bkreider
 
  recipe-maintainers:
    - dhirschfeld
    - tiangolo
    - synapticarbors
