{% set name = "fastapi" %}
{% set version = "0.115.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-{{ version }}.tar.gz
  sha256: 9d7da3b196c5eed049bc769f9475cd55509a112fbe031c0ef2f53768ae68d13f

build:
  entry_points:
    - fastapi = fastapi.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 
    - pdm-backend
    - pip
  run:
   - python
   # [project.dependencies]
   - starlette >=0.45.3
   - typing_extensions
   - pydantic
   # [project.optional-dependencies.standard]
   - email_validator
   - fastapi-cli
   - httpx
   - jinja2
   - python-multipart
   - uvicorn-standard
test:
  imports:
    - fastapi
  commands:
    - pip check
    - fastapi --help
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
  homepage: https://github.com/fastapi/fastapi
  repository: https://github.com/fastapi/fastapi
  documentation: https://fastapi.tiangolo.com

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/70829
    reason: Dependency for chromadb
  recipe-maintainers:
    - ianaobi
    - bkreider
  recipe-maintainers:
    - dhirschfeld
    - tiangolo
    - synapticarbors
    - bollwyvl
