{% set name = "fastapi" %}
{% set version = "0.56.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35394a965e66af64b64f0ce18d5ab49403876eabf0f6a4f2f2a20f794214997b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit
  run:
    - python >=3.6
    - starlette =0.13.2
    - pydantic >=0.32.2,<2.0.0a0

test:
  imports:
    - fastapi
    - fastapi.dependencies
    - fastapi.middleware
    - fastapi.openapi
    - fastapi.security

about:
  home: https://github.com/tiangolo/fastapi
  license: MIT
  license_file: LICENSE
  summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
  doc_url: https://github.com/tiangolo/fastapi
  dev_url: https://github.com/tiangolo/fastapi

extra:
  recipe-maintainers:
    - dhirschfeld
    - tiangolo
    - synapticarbors
