{% set name = "fastapi" %}
{% set version = "0.115.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-{{ version }}.tar.gz
  sha256: b1de15cdc1c499a4da47914db35d0e4ef8f1ce62b624e94e0e5824421df99739

build:
  entry_points:
    - fastapi = fastapi.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pdm-backend
    - pip
    - python
  run:
    - python
    # [project.dependencies]
    - starlette >=0.46.2
    - typing_extensions
    - pydantic
    # [project.optional-dependencies.standard]
    - email_validator
    - fastapi-cli
    - httpx
    - jinja2
    - python-multipart
    - uvicorn-standard
test:
  imports:
    - fastapi
  commands:
    - pip check
    - fastapi --help
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
  homepage: https://github.com/fastapi/fastapi
  repository: https://github.com/fastapi/fastapi
  documentation: https://fastapi.tiangolo.com

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/70829
    reason: Dependency for chromadb
  recipe-maintainers:
    - ianaobi
    - bkreider
  recipe-maintainers:
    - dhirschfeld
    - tiangolo
    - synapticarbors
    - bollwyvl
