travis:
  secure:
    BINSTAR_TOKEN: Znqz5S2Wpk7nRaUzLlTNPZDZ1Ad8V2nm1wFOBAagpeNfSqR6Jzt39hHkKo/uzSqCv9svEqqEFzMVjQSjxLUXRLSXqfYeApTb88j5BQjfeUyMeLqKyKalp5G+NBteyuiXpDmwf7rHskskNqG/ESaQXU6EBbRGFg+6b4mH3xSTSvCPNQksdMhLQpY2zXGByp/CWF4/vAS+mZsPgm72e55kgGs40aSLB/TVA8GCekGAev2TDN5tIblTP0uYk+UlJQ0wegux56ThT3nHnX/0oiiiyD33sjpZYMJN/XPPkjkd62X3tnFR8ARhxC3KMImlFbkkXZWz2Yiw6yhDS40K3NsJQTHjSeFQ4xDcQ/vsbgOgsFK1pZWfiske0yGyWvokwK39lpqA6iWGGRk2HKtBEdCyyJKpiKSvxtqLrOfWcY9PwgXJcZE9tyIUcF0gx41NcIaLHpE8NkUrYZGPejjpXSgfkzVUYAxjt1skFLb+KkOIcygM0qO/C1Ie9zDAbekFHwsxf6OUC2CxtvXsKiknLGG/9LRSIf7hUZueqQDB8zQzm5m5RHHtW4xQym5QtD2G8nFgcot9fhbKEohiYM4hy6nbP0NTx8uCN1RVvpZSYT6yaoATho8MhpIqiM1v0DCCCC2269Qg+tKDjTdBOvwBCuScucIBi9jwvN8if4pOQAZ8YnM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
